### ISSUE TITLE
Skip unknown thread type: MARKETPLACE

### ISSUE THREAD

**Issue by mileyvirus** [karlicoss/fbmessengerexport#2]
Hey @karlicoss, I just cloned the repo and after logging in I started the `export.py` script and boom: `fbchat._exception.FBchatException: Unknown thread type: MARKETPLACE`.

It was my first thread and I think it's for conversations happening with Facebook Marketplace users. [Apparently it's a bug with fbchat](https://github.com/carpedm20/fbchat/issues/408).

I think we should skip this thread type for now at least until fbchat resolves the open issue.

**Comment by karlicoss** [comment]
Hey, appreciate for linking straight to the upstream issue!

I pushed branch `hack-marketplace` as a workaround, can you let me know if it works for you? I'm kind of fixing it blidnfolded, as I don't have any marketplace threads, but I think it should work! You should see warnings instead of the script crashing.

If it works for you, I'll merge in master: https://github.com/karlicoss/fbmessengerexport/pull/3

**Comment by jcguu95** [comment]
Started trying yesterday, I encountered the same problem. The `hack-marketplace` branch worked for me. Thank you so much!

**Comment by karlicoss** [comment]
Sweet. Merged in master, thanks for confirming :)

**Comment by mileyvirus** [comment]
Hey there! I forgot to reply and since I got notified by your comments I saw, I'm so sorry… as @jcguu95 confirmed it definitely worked. Thank you 🙏
