### ISSUE TITLE
Fetching specific threads

### ISSUE THREAD

**Issue by jcguu95** [karlicoss/fbmessengerexport#6]
Thank you for making this package! I'd like to know if it's possible to alter the code in this repo, in order to fetch data from a specific thread? For example, 

```
fetch --thread "Alexander Mojae" --date_b "2020-06-01" --date_e "2020-06-10"
```

Mainly I want to backup "useful" conversations every now and then.. but running the whole process takes too much time.

**Comment by karlicoss** [comment]
Hey, yep, sure! The simplest and cleanest would be to alter the code here: https://github.com/karlicoss/fbmessengerexport/blob/aeb53cf66a0015a3fc4fb2f800800cfec95e8c90/export.py#L198

, and discard the threads that don't match the name/id/whatever you prefer. 
I guess you won't need the start/end dates then because the tool works iteratively: it would fetch everything the first time, but on the subsequent runs -- only missing bits.
Let me know if that helps!

**Comment by jcguu95** [comment]
It'd definitely help after I get familiar with python. Thanks for the hint :smile:

**Comment by jcguu95** [comment]
Finally got some time to learn python.

### Fuzzily select threads with dmenu

A primitive snippet that allows me to use `dmenu` to quickly select a sublist of names from the list `thr`, and only fetch their data.

Simply replace `threads.extend(thr)` you mentioned above by

```
        # Depends on python3 and dmenu.
        thr_names = (list(map(lambda x: x.name, thr)))
        command = 'echo -e \"' \
                + '\\n' \
                + '\\n'.join([str(elem) for elem in thr_names]) \
                + '\" | ' \
                + 'dmenu -i'
        import subprocess
        selected_names = []
        while True:
            selected = (subprocess.check_output(command , shell=True, text=True)).strip("\n")
            if selected != "":
                selected_names.append(selected)
            else: break
        print("selected_names : ", selected_names)
        filtered = [ x for x in thr if (x.name in selected_names) ]
        print("filtered : ", filtered)
        thr = filtered
        input("Press Enter to continue the whole process.")
        threads.extend(thr)
```

### Select timestamp?

There's a comment in the source

```
# sadly, api only allows us to fetch messages from newest to oldest
# that means that we have no means of keeping contiguous chunk of messages in the database,
# and 'extending' it both ways
# we can do extend if to the left (i.e. to the oldest)
# but all newer messages have to be accumulated and written in a single transaction
```

Do you happen to know if it still holds?

**Comment by karlicoss** [comment]
Nice, well done :) `dmenu` is a bit extreme in general for this project (because it's meant to be running in terminal without user intervention), but glad you hacked it for yourself!

> Do you happen to know if it still holds?

I haven't tested, but pretty sure it hasn't changed. Plus, the upstream `fbchat` library is a bit abandoned, so sadly not sure about the future of all this at all. Potentially will have to switch to a different library, or something -- maybe it has a different way...
